### ISSUE TITLE
Style Meeting Minutes: General CSS Topic

### ISSUE THREAD

**Issue by w3dong** [w3dong/fa22-cse110-lab3#1]
**Sub-task to complete**
- [x] 3 ways of css: in-line, internal, external
- [x] Comment
- [x] Color
- [x] Background (Color)
- [x] Use 3 unique relative units total
- [x] Use 3 unique absolute units total
- [x] Margin     /* spacing between html elements */)
- [x] Padding     /* spacing within html elements */
- [x] Boarders /* borders around html elements */
- [x] Text     /* style your text */
- [x] Display  /* block displayment */
- [x] Sizing     /* set the height and width for an element */    
- [x] Position
- [x] Psudo-class
- [x] Layouts
- [x] Responsiveness
- [x] Fonts
